### ISSUE TITLE
Running the example creates an epub with an errror

### ISSUE THREAD

**Issue by gsmedley** [imgurbot12/pypub#13]
When I open the example epub I get a message on the first page:

“This page contains the following errors:error on line 4 at column 62: Entity 'nbsp' not defined”

**Comment by imgurbot12** [comment]
Hey @gsmedley, sorry to hear you're having issues. Would you be willing to provide a few more details about your problem so I can help diagnose it please? What version of python and pypub are you using? Are you talking about the spacebattles example in the examples folder or the simple wikipedia one in the readme?

**Comment by gsmedley** [comment]
It's the wikipedia one in the readme. Versions are: Python 3.10.9; pypub3 2.0.2. I'm reading the epub with Apple Books and seeing this:

<img width="945" alt="Screenshot 2023-10-17 at 7 29 03 AM" src="https://github.com/imgurbot12/pypub/assets/30830/597b725f-5425-472b-ae5d-612c9d0ee13c">

**Comment by imgurbot12** [comment]
@gsmedley ah ok thanks. So the library was including escape characters that the epub format does not support. gotcha. I've just issued a [PR](https://github.com/imgurbot12/pypub/pull/14) with a few upgrades to hopefully fix this along with a few other possible epub compliance issues moving forward.

Version 2.0.3 was just released so feel free to upgrade and give it a shot. I unfortunately don't have any apple devices to test with so please let me know if that worked for you or if you encounter any other issues. Thanks!

**Comment by imgurbot12** [comment]
@gsmedley did those changes end up working for you?

**Comment by gsmedley** [comment]
I didn't have a chance to look at it yet, I will be back to work tomorrow so will let you know.

**Comment by gsmedley** [comment]
Sorry it took me a while to get back to this, this is working for me now. Thanks!

**Comment by imgurbot12** [comment]
Good to hear it. Thanks! Gonna close this issue but feel free to reopen if you'd like
