### ISSUE TITLE
Style files added to "css_paths" get copied to the epub, but not included

### ISSUE THREAD

**Issue by gsmedley** [imgurbot12/pypub#16]
For example:
```
css_path "path/to/my.css"
epub = pypub.Epub("title")
epub.css_paths = [css_path]
etc.
```

Will add the css file to the package:
```
  inflating: OEBPS/styles/my.css   
  inflating: OEBPS/styles/styles.css  
```

But not include it in the page HTML:

```
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <link type="text/css" rel="stylesheet" href="styles/styles.css"/>
    <title>Test Title</title>
  </head>

```

**Comment by imgurbot12** [comment]
Similar to table support, the PR I just pushed should include fixes to ensure the extra css gets included in the epub. Pushed to pypi under `2.0.4`. Please update and let me know how it goes for you. Thanks again for helping resolve issues like this :)

**Comment by gsmedley** [comment]
Thanks for looking at these! Working great!

**Comment by gsmedley** [comment]
Thanks!
