### ISSUE TITLE
Dependency on deprecated imghdr

### ISSUE THREAD

**Issue by letrec** [imgurbot12/pypub#21]
imghdr has been deprecated as of Python 3.11 and removed as of Python 3.13. (see https://peps.python.org/pep-0594/ for details), so the project is unusable on 3.13 and above.
Are there any workarounds?

**Comment by imgurbot12** [comment]
Good point! I had forgotten that was happening. I even thought about changing it a while back but i guess i forgot lol.

The PEP itself offers some decent 3rd party library alternatives. With a quick glance through some of them it seems like [filetype](https://pypi.org/project/filetype/) does the job quite nicely.

Will make a PR with a replacement and push a new release. Thanks for reminding me :)

**Comment by imgurbot12** [comment]
PR merged https://github.com/imgurbot12/pypub/pull/22
Release published: https://pypi.org/project/pypub3/2.0.6/

Thanks again :)
