### ISSUE TITLE
Cover Image not applied correctly on Windows

### ISSUE THREAD

**Issue by daWinzig** [imgurbot12/pypub#23]
The img tag in _OEBPS/coverpage.xhtml_ generates with a backslash as the path separator on Windows instead of a forward slash, causing it to not show in the final epub.

From what I can tell not using [_os.path.join([...])_](https://github.com/imgurbot12/pypub/blob/27916684c52ac2a6aa1e181ca4601ab62d2c3006/pypub/builder.py#L216C9-L216C54) to concatenate the path should fix it.

**Comment by imgurbot12** [comment]
Oh interesting. Nice catch, sorry about that.

I unfortunately don't have a windows box to test with at this moment, but I just pushed [a potential fix to a new branch](https://github.com/imgurbot12/pypub/commit/f33ee21b1e8457806899eed816ef31ffc00f038e).
Would you be willing to test the changes please?

You can install the library directly from github at the specified branch with the following command:
```python3
pip install git+https://github.com/imgurbot12/pypub.git#fix/windows -U
```

lmk if that works for you, thanks :)

**Comment by daWinzig** [comment]
That did the trick, thank you for the quick response!

**Comment by daWinzig** [comment]
But only when using PNG, not for JPG. That is most probably a different issue all together though.

Edit: Okay, figured it out. While _.jpg_ and _.jpeg_ are exchangeable as file extensions, the mime type has to be _image/jpeg_.
A potential solution would be to use the [mimetypes module](https://docs.python.org/3/library/mimetypes.html) to guess the type based off the file extension [here](https://github.com/imgurbot12/pypub/blob/27916684c52ac2a6aa1e181ca4601ab62d2c3006/pypub/builder.py#L246C25-L246C72) and under _images_ a few lines below.

**Comment by imgurbot12** [comment]
> That did the trick, thank you for the quick response!

Yeah ofc, glad it worked. Thanks for the bug report :)

> But only when using PNG, not for JPG. That is most probably a different issue all together though.

Hmm interesting, it may be an issue with your epub reader or maybe even just an improper extension to the file itself. If you specify a custom cover for the epub, the script just [copies that file into the epub](https://github.com/imgurbot12/pypub/blob/27916684c52ac2a6aa1e181ca4601ab62d2c3006/pypub/builder.py#L208-L209) without changing the filename or contents.

The cover page XHTML just [references the image source](https://github.com/imgurbot12/pypub/blob/27916684c52ac2a6aa1e181ca4601ab62d2c3006/pypub/templates/coverpage.xhtml.j2#L15) with the existing file extension without declaring any mimetype so I'm not sure why you would be having issues with various extensions unless the reader interprets it wrong or something.

**Comment by daWinzig** [comment]
The cover XHTML file itself is fine, the problem comes from the declaration inside the book.opf, specifically [here](https://github.com/imgurbot12/pypub/blob/master/pypub%2Ftemplates%2Fbook.opf.j2#L25) (even though the other images may be also affected).
See above on where it is implemented in the builder.py script.

Edit: I don't think this should be an os issue, so it should be possible to reproduce by just giving it a file with an .jpg extension

**Comment by imgurbot12** [comment]
> the problem comes from the declaration inside the book.opf

Ah good catch. I should stop working on issues like this when I'm tired lol. The mimetypes library was a great suggestion. Implemented and pushed to `fix/windows` branch, you should be able to run the same pip command I posted above to update and test.

Please let me know if that works for you.

**Comment by daWinzig** [comment]
works great, thank you :)

**Comment by imgurbot12** [comment]
Changes merged with master. version [2.0.7](https://pypi.org/project/pypub3/2.0.7/) was just published to pypi.

Thanks for the report and your help finding the issue :)
