### ISSUE TITLE
Cannot set custom cover images

### ISSUE THREAD

**Issue by chrrel** [imgurbot12/pypub#9]
When specifiying an own cover image, the programs runs into an exceptionj: *RuntimeError: cannot render_chapter before `begin`*.

The following script can be used to reproduce this issue (note that the file must be named `cover.png`).

```python
import pypub

ebook = pypub.Epub(title="Test", cover="/home/user/cover.png")
c = pypub.create_chapter_from_html(html="<p>Test</p>".encode())
ebook.add_chapter(c)
ebook.create("test.epub")
```

This can be fixed by moving [line 208 in builder.py](https://github.com/imgurbot12/pypub/blob/master/pypub/builder.py#L208) before line 201. Using this approach will make sure that `self.template` is defined also when using a custom cover.

**Comment by imgurbot12** [comment]
Hey @chrrel, thanks for the bug reports! I just pushed a hotfix for this and the other issue you mentioned recently. Version `2.0.1` was just published to pypi as well so please let me know if those patches worked for you.

**Comment by chrrel** [comment]
Tested it using the pypi version. Works like a charm. Thanks for this incredibly fast fix.

**Comment by imgurbot12** [comment]
> Tested it using the pypi version. Works like a charm. Thanks for this incredibly fast fix.

Happy to help :)
